FROM docker.io/golang:1.21 AS builder

WORKDIR /go/src/github.com/ffromani/ghwadvisor
COPY . .

# Build
RUN make binaries-static

FROM scratch
COPY --from=builder /go/src/github.com/ffromani/ghwadvisor/_out/ghwadvisor /ghwadvisor
EXPOSE 8080/tcp
ENTRYPOINT ["/ghwadvisor"]
